import { builtinModules } from "node:module";

import esbuild from "esbuild";
import fs from "node:fs";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/** @type {import("esbuild").Plugin} */
const renameCSSPlugin = {
  name: "Rename CSS",
  setup: (build) => {
    build.onEnd(() => {
      if (fs.existsSync("dist/main.css")) {
        fs.renameSync("dist/main.css", "dist/styles.css");
      }
    });
  },
};
const context = await esbuild.context({
  // General options
  bundle: true,
  // Input
  entryPoints: ["src/main.ts"],
  // Output contents
  banner: { js: banner },
  format: "cjs",
  // Output locations
  outfile: "dist/main.js",
  // Path resolution
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  // Transformation
  target: "es2018",
  // Optimization
  minify: prod,
  treeShaking: true,
  // Source maps
  sourcemap: prod ? false : "inline",
  // Logging
  logLevel: "info",
  // Plugins
  plugins: [
    // Reference: https://svelte.dev/docs/svelte/svelte-compiler#CompileOptions
    // When using "injected", the generated code will inject css into the <style> tag under <head>,
    // because obsidian hot reload will not clean it on each reload, modified css will not be hot
    // reloaded when using "injected"

    // Therefore we have to use "external" to let css hot reload work
    // Another benefit of using "external" is minimizing the size of generated js file
    esbuildSvelte({
      compilerOptions: { css: "external" },
    }),
    renameCSSPlugin,
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
